### ISSUE TITLE
Use a power of two for calling cpp11::check_user_interrupt()

### ISSUE THREAD

**Issue by krlmlr** [davidchall/bignum#32]
I noticed several checks of the form `x % 10000 == 0` in the code. This check is slower than e.g. `x % 16384 == 0` or `x % 8192 == 0` or even `x & 0x1fff`, because the latter only needs a logical AND, whereas the former uses a full-fledged integer division.

I suspect these tight loops will run a bit faster when employing the alternative variants. I haven't found a good source that demonstrates the actual impact, we're probably talking microseconds for a typical operations at best.

**Comment by davidchall** [comment]
Hi @krlmlr,

Thanks for the feedback! I was curious about whether this theoretical performance benefit is borne out by the C++ compiler, so I did a bit of benchmarking.

The results below exhibit no significant difference between the techniques, but the existing modulo method has the benefit that it is easier to understand. Please let me know if I misunderstood your recommendation - thanks!

``` r
cpp11::cpp_function('void modulo(int n) {
  for (int i=0; i<n; ++i) {
    if (i % 10000 == 0) { }
  }
}')

cpp11::cpp_function('void bitwise(int n) {
  for (int i=0; i<n; ++i) {
    if (i & 0xffff == 0xffff) { }
  }
}')


n <- 1e8
results <- bench::mark(modulo(n), bitwise(n))

results
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 modulo(n)    2.51µs   2.89µs   275213.        0B        0
#> 2 bitwise(n)   2.53µs   2.83µs   308840.        0B        0

ggplot2::autoplot(results)
#> Loading required namespace: tidyr
```

![](https://i.imgur.com/Ck63e58.png)

<sup>Created on 2021-11-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by krlmlr** [comment]
Thanks. Computing `% 8192` or `% 16384` gives the same improvement without sacrificing readability, perhaps `% 0x2000` is easier to read?

The itr/sec indicates a 10% improvement, but it's not reflected in the median measurement. Also, could the compiler have optimized the loop away entirely?

**Comment by davidchall** [comment]
You were absolutely right - the compiler was optimizing away the condition, so those benchmarks were meaningless.

Here's the updated version (the bitwise approach is the clear winner):

``` r
cpp11::cpp_function('int modulo10(int n) {
  int out = 0;
  for (int i=0; i<n; ++i) {
    if (i % 10000 == 0) out += 1;
  }
  return(out);
}')

cpp11::cpp_function('int modulo2(int n) {
  int out = 0;
  for (int i=0; i<n; ++i) {
    if (i % 8192 == 0) out += 1;
  }
  return(out);
}')

cpp11::cpp_function('int bitwise(int n) {
  int out = 0;
  for (int i=0; i<n; ++i) {
    if (i & 0x2000 == 0x2000) out += 1;
  }
  return(out);
}')



n <- 1e8
results <- bench::mark(modulo10(n), modulo2(n), bitwise(n), check = FALSE)

results
#> # A tibble: 3 × 6
#>   expression       min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>  <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 modulo10(n)  56.15ms  57.55ms      17.2        0B        0
#> 2 modulo2(n)   10.97ms  11.79ms      85.0        0B        0
#> 3 bitwise(n)    5.37ms   5.59ms     175.         0B        0

ggplot2::autoplot(results)
#> Loading required namespace: tidyr
```

![](https://i.imgur.com/pIxs0F0.png)

<sup>Created on 2021-11-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by krlmlr** [comment]
Thanks for looking into this. I'm astonished by the magnitude of this effect even on modern processors.

**Comment by davidchall** [comment]
I'm also very surprised by the magnitude of the performance benefit - I'll need to update some other packages too! 😅

**Comment by davidchall** [comment]
Hi again @krlmlr,

I've just realized why `bitwise()` is so much faster than `modulo2()` is the above benchmarking. It's because the `==` operator takes precedence over the `&` operator (so we need some parentheses for this to work correctly). Once this is done, the benchmarking shows these two functions are very similar (in fact, `modulo2()` has a slight advantage).

``` r
cpp11::cpp_function('int modulo10(int n) {
  int out = 0;
  for (int i=0; i<n; ++i) {
    if (i % 10000 == 0) out += 1;
  }
  return(out);
}')

cpp11::cpp_function('int modulo2(int n) {
  int out = 0;
  for (int i=0; i<n; ++i) {
    if (i % 8192 == 0) out += 1;
  }
  return(out);
}')

cpp11::cpp_function('int bitwise(int n) {
  int out = 0;
  for (int i=0; i<n; ++i) {
    if ((i & 0x2000) == 0x2000) out += 1;
  }
  return(out);
}')



n <- 1e8
results <- bench::mark(modulo10(n), modulo2(n), bitwise(n), check = FALSE)

results
#> # A tibble: 3 × 6
#>   expression       min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>  <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 modulo10(n)   55.9ms     57ms      17.2        0B        0
#> 2 modulo2(n)    10.8ms   10.9ms      89.5        0B        0
#> 3 bitwise(n)    11.1ms   11.4ms      82.0        0B        0

ggplot2::autoplot(results)
#> Loading required namespace: tidyr
```

![](https://i.imgur.com/sVc48xw.png)

<sup>Created on 2021-11-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
