### ISSUE TITLE
Allow leading zeros

### ISSUE THREAD

**Issue by tyner** [davidchall/bignum#37]
It would be nice if biginteger() supported leading zeros. Currently (under version 0.3.0) it returns NA:

```r
biginteger("08")
```
gives

```
<biginteger[1]>
[1] <NA>
```

**Comment by davidchall** [comment]
Thanks for the report, @tyner. The behavior with leading zeros is untrustworthy. Sometimes it returns the expected result, sometimes it returns NA, and sometimes it returns the wrong result. See reprex below.

``` r
library(bignum)

# without leading zeros
biginteger(c("1", "4", "7", "8", "10"))
#> <biginteger[5]>
#> [1] 1  4  7  8  10

# with leading zeros
biginteger(c("01", "04", "07", "08", "010"))
#> <biginteger[5]>
#> [1] 1    4    7    <NA> 8
```

<sup>Created on 2023-04-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
